### ISSUE TITLE
Retrying download gem

### ISSUE THREAD

**Issue by ChandraJangam-th** [avo-hq/main.avodemo.com#25]
Retrying download gem from https://packager.dev/avo-hq/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-dynamic_filters-3.7.4.gem)

**Comment by adrianthedev** [comment]
You are probably seeing that error because you don't have the Advanced tier gem token.

The avodemo.com app uses the paid gems to highlight all the features of Avo.
You can see all of the gems and features on the [pricing page](https://avohq.io/pricing).

Once you purchase an advanced license you can add it to the `.env` file (copied from [this one](https://github.com/avo-hq/main.avodemo.com/blob/main/.env.sample#L10)) and follow the instructions here and install it

**Comment by adrianthedev** [comment]
Closign for now, but let me know if anything new pops up.
